Chain-FMac,
 Sat Nights Alright-EJohn,
 Take it Easy-Eagles,
 Stairway-LZep,
 MoneyforNothing-DStraights,
 Bat out of Hell-Meatloaf,
 Comfrtly Numb-Floyd,
 Hotel California-Eagles,
 Blinded by Light-ManfredMEarthband,
 Long Train Running-Doobies,
 Telegraph Road-DStraights,
 Reeling in Years-Steely Dan,
 Logical Song-Supertramp,
 Mr Blue Sky-ELO,
 More than a Feeling-Boston,
 Freebird-Skynyrd,
 With a Little Help-JCocker, and more